apps/masterlist/urls.py
from django.urls import path
from apps.masterlist import views
from . import views
from .views import (MasterlistUpload, MasterlistView, 
                    MasterlistModifyView, MasterlistUpdate, 
                    BulkUpdateInit)
from apps.authentication.views import add_agency

urlpatterns = [
    path("", MasterlistView.as_view(), name="masterlist"),
    path("modify-list/", MasterlistModifyView.as_view(), name="modifylist"),
    path("list-add/", MasterlistUpload.as_view(), name="listadd"),
    path("modify-list/list-edit/<int:pk>", MasterlistUpdate.as_view(), name="listedit"),
    path("add-option", add_agency, name="add_agency"),
    path("bulk-update-init", BulkUpdateInit.as_view(), name="bulk_update_init"),
    path('cancel-submission-masterlist/', views.cancel_submission_masterlist, name='cancel_submission_masterlist'),
    path('submit-masterlist/', views.submit_masterlist, name='submit_masterlist'),
]

apps/report/urls.py
from django.urls import path
from apps.report import views
from . import views

urlpatterns = [
    path("", views.report, name="report"),
    path('download-pm-report/', views.download_pm_report, name='download_pm_report'),
    path('download-jkk-report/', views.download_jkk_report, name='download_jkk_report'),
]

apps/validation/urls.py
from django.urls import path
from .views import ValidationView
from . import views

urlpatterns = [
    path("", ValidationView.as_view(), name="validation"),
    path("edit-note/", views.edit_note, name="edit_note"),
    path("validate-data/", views.validate_data, name="validate_data"),
    path("validate-data-comments/", views.validate_data_comments, name="validate_data_comments"),
    path("push-data/", views.push_data, name="push_data"),
    path("push-data-comments/", views.push_data_comments, name="push_data_comments"),
    path("delete-data/", views.delete_data, name="delete_data"),
    path("push-data-report/", views.create_dag_run, name="push_data_report"),
]

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path("Xlh7K35!tp0/", admin.site.urls),          # Django admin route
    path("", include("apps.authentication.urls")), # Auth routes - login / register
    path("", include("apps.home.urls")),           # UI Kits Html files
    path("history/", include("apps.history.urls")),
    path("upload/", include("apps.upload.urls")),    
    path("data-cleaning/", include("apps.datacleaning.urls")),  
    path("masterlist-budget/", include("apps.masterlist.urls")), # link for apps function not html page.... multiple html page can be under a template folder
    path("masterlist-nec/", include("apps.masterlistnec.urls")), # link for apps function not html page.... multiple html page can be under a template folder
    path("soalan-lazim/", include("apps.faq.urls")),
    path("report/", include('apps.report.urls')),
    path("validation/", include('apps.validation.urls')),
    path("data-catalogue/", include('apps.datacatalogue.urls')),
    path("inventory/", include('apps.inventory.urls')),
    path("validation/", include('apps.validation.urls')),
]

handler404 = "core.error.page_not_found"
handler500 = "core.error.server_error"
handler403 = "core.error.permission_denied"

apps/masterlist/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from django.core.files.storage import FileSystemStorage
from django.conf import settings
from apps.upload.models import AgencyList
from core.choices import STATUS, STATUS_VAL

private_storage = FileSystemStorage(location=settings.PRIVATE_STORAGE_ROOT_MASTERLIST)

class FileMasterlist(models.Model):
    Fail = models.FileField(storage=private_storage, validators=[FileExtensionValidator(allowed_extensions=['xlsx', 'xls', 'csv'])])
    
    def __str__ (self):
        return str(self.Fail)

class Validation(models.Model):
    reporting_date = models.DateTimeField(null=True, blank=True)
    agency = models.CharField(max_length=50, null=True, blank=True)
    init_id = models.CharField(max_length=15, null=True, blank=True)
    init_name = models.CharField(max_length=1000, null=True, blank=True)
    bene_last_month = models.IntegerField(null=True, blank=True)
    bene_this_month = models.IntegerField(null=True, blank=True)
    disb_last_month = models.FloatField(null=True, blank=True)
    disb_this_month = models.FloatField(null=True, blank=True)
    applied_amount = models.FloatField(null=True, blank=True)
    approved_amount = models.FloatField(null=True, blank=True)
    status = models.CharField(max_length=100, choices=STATUS, null=True, blank=True)
    failed_reason_user =  models.CharField(max_length=1000, null=True, blank=True)
    edit_note_by = models.CharField(max_length=100, null=True, blank=True)
    date_modified_note = models.DateTimeField(null=True, blank=True)
    is_validate = models.CharField(max_length=100, choices=STATUS_VAL, null=True, blank=True)
    is_push = models.BooleanField(default=False, null=True, blank=True)
    cur_note = models.TextField(null=True, blank=True)
    validate_by = models.CharField(max_length=200, null=True, blank=True)
    push_by = models.CharField(max_length=200, null=True, blank=True)
    validation_date = models.DateTimeField(null=True, blank=True)
    push_date = models.DateTimeField(null=True, blank=True)
    date_modified = models.DateTimeField(null=True, blank=True)
            
    class Meta:
        verbose_name = "Validation"
        verbose_name_plural = "Validation"

class Note(models.Model):
    date_modified = models.DateTimeField(null=True, blank=True)
    note_assc_id = models.CharField(max_length=15, blank=True, null=True)
    note_assc_name = models.CharField(max_length=500, blank=True, null=True)
    editor = models.CharField(max_length=200, blank=True, null=True)
    text_note = models.TextField(blank=True, null=True)
    
    class Meta:
        verbose_name = "Validation note"
        verbose_name_plural = "Validation notes"

apps/masterlistnec/models.py
from django.db import models

# Create your models here.

apps/report/models.py
from django.db import models

# Create your models here.

apps/validation/models.py
from django.db import models

# Create your models here.

apps/masterlist/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import ListView, UpdateView, FormView, View
from apps.upload.models import (MasterlistBudget, DisburseMinistry, GeneralRemark, 
                                AllocationMinistry, MasterlistBudgetLog, UserProfile)
from django.urls import reverse_lazy
from .forms import MasterlistForm, FileFormMasterlist, MasterlistFormEdit
from django.conf import settings
import datetime as dt
from django.utils.decorators import method_decorator
from core.decorators import restrict_user
from django.contrib.auth.decorators import login_required
import logging
from django.shortcuts import HttpResponse, redirect, render
from django.contrib import messages
import datetime as dt
from pyzabbix import ZabbixMetric, ZabbixSender
from django.db.models import Q
import pandas as pd
from django.utils.text import get_valid_filename
from django.views.decorators.csrf import csrf_protect
import os
import datetime as dt
from django.db.models import F

mainPath = settings.MAINPATH
logger = logging.getLogger('main')
zabbix_sender = ZabbixSender(settings.ZABBIX_SERVER, settings.ZABBIX_PORT)

decorators = [login_required(login_url="/login/"), restrict_user("pid_group")]
@method_decorator(decorators, name='dispatch')
class MasterlistView(ListView):
    """_summary_
    Render masterlist page for both PIDs and Lead PIDs

    Args:
        ListView (_type_): _description_

    Returns:
        _type_: _description_
    """    
    model = MasterlistBudget
    template_name = 'pid/masterlist.html'
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['object'] = MasterlistBudget.objects.filter(is_active=True).filter(
            Q(program_code='B23') | Q(program_code='B23 + NEC')).order_by(
            F('date_modified').desc(nulls_last=True))
        context['userprofile'] = UserProfile.objects.all()
        return context
    

@method_decorator(decorators, name='dispatch')
class MasterlistModifyView(ListView):
    """_summary_
    Render modifylist page for both PIDs and Lead PIDs (With edit button)

    Args:
        ListView (_type_): _description_

    Returns:
        _type_: _description_
    """    
    model = MasterlistBudget
    template_name = 'pid/modifylist.html'

    def get_queryset(self):
        return MasterlistBudget.objects.filter(is_active=True).filter(
            Q(program_code='B23') | Q(program_code='B23 + NEC')).order_by(
            F('date_modified').desc(nulls_last=True))


@method_decorator(decorators, name='dispatch')
class MasterlistUpload(SuccessMessageMixin, FormView):
    """_summary_
    Class for add masterlist

    Args:
        SuccessMessageMixin (_type_): _description_
        FormView (_type_): _description_

    Returns:
        _type_: _description_
    """    
    form_class = MasterlistForm
    template_name = 'pid/listadd.html'
    success_message = "Inisiatif baru telah ditambah"
    success_url = reverse_lazy('masterlist')

    def form_valid(self, form):
        obj = MasterlistBudget()
        obj.tekad = form.cleaned_data['tekad']
        obj.ikhtiar = form.cleaned_data['ikhtiar']
        obj.sub_1 = form.cleaned_data['sub_1']
        obj.sub_2 = form.cleaned_data['sub_2']
        obj.init_name = form.cleaned_data['init_name']
        obj.subinit_name = form.cleaned_data['subinit_name']
        obj.allocation = form.cleaned_data['allocation']
        obj.cur_disb = form.cleaned_data['cur_disb']
        obj.cur_remark = form.cleaned_data['cur_remark']
        obj.ministry = form.cleaned_data['ministry']
        obj.agency = form.cleaned_data['agency']
        obj.category = form.cleaned_data['category']
        obj.status = form.cleaned_data['status']
        obj.nec_id = form.cleaned_data['nec_id']
        obj.stf = form.cleaned_data['stf']
        obj.category_nec = form.cleaned_data['category_nec']
        obj.program = form.cleaned_data['program']
        obj.target = form.cleaned_data['target']
        obj.is_active = True
        obj.modified_by = self.request.user.username
        obj.date_modified = dt.datetime.now()

        
        if (not obj.sub_1 and not obj.sub_2) or (not obj.sub_1):
            obj.init_id = str(obj.tekad) + str(obj.ikhtiar)
            obj.sub_init_id = str(obj.tekad) + str(obj.ikhtiar)
        elif not obj.sub_2:
            obj.init_id = str(obj.tekad) + str(obj.ikhtiar) + '_' + str(obj.sub_1)
            obj.sub_init_id = str(obj.tekad) + str(obj.ikhtiar) + '_' + str(obj.sub_1)
        else:
            obj.init_id = str(obj.tekad) + str(obj.ikhtiar) + '_' + str(obj.sub_1) + '_' + str(obj.sub_2)
            obj.sub_init_id = str(obj.tekad) + str(obj.ikhtiar) + '_' + str(obj.sub_1) + '_' + str(obj.sub_2)
        
        if obj.sub_init_id and obj.nec_id:
            obj.program_code = "B23 + NEC"
        elif obj.sub_init_id:
            obj.program_code = "B23"
        else:
            pass
        
        obj.save()
        MasterlistBudgetLog(subinit_name=obj.subinit_name, date_modified=dt.datetime.now(), 
                            sub_init_id=obj.sub_init_id, requestor=self.request.user.username).save()
        
        if obj.cur_disb:
            DisburseMinistry(subinit_name=obj.subinit_name, disb=obj.cur_disb, 
                             date_modified=dt.datetime.now(), sub_init_id=obj.sub_init_id, 
                             requestor=self.request.user.username).save()
        
        if obj.cur_remark:
            GeneralRemark(subinit_name=obj.subinit_name, remark=obj.cur_remark, 
                          date_modified=dt.datetime.now(), sub_init_id=obj.sub_init_id, 
                          requestor=self.request.user.username).save()
        
        if obj.allocation:
            AllocationMinistry(subinit_name=obj.subinit_name, alct=obj.allocation, 
                               date_modified=dt.datetime.now(), sub_init_id=obj.sub_init_id, 
                               requestor=self.request.user.username).save()
        
        logger.info("Upload initiative " + str(obj.subinit_name) + " - " + str(self.request.user.username))
        try:
            packet = [ZabbixMetric('CentOS PODS Dev Master', 'django.log.user_activity', 
                                   "Upload initiative " + str(obj.subinit_name) + " - Pending for Lead PID approval - " 
                                   + str(self.request.user.username))]
            zabbix_sender.send(packet)
        except:
            pass

        return super().form_valid(form)


@method_decorator(decorators, name='dispatch')
class MasterlistUpdate(SuccessMessageMixin, UpdateView):
    """_summary_
    Class for update masterlist

    Args:
        SuccessMessageMixin (_type_): _description_
        UpdateView (_type_): _description_

    Returns:
        _type_: _description_
    """    
    model = MasterlistBudget
    form_class = MasterlistFormEdit
    template_name = 'pid/listedit.html'
    success_message = "Inisiatif anda telah dikemaskini"
    success_url = reverse_lazy('modifylist')

    def form_valid(self, form):
        allocation = form.cleaned_data['allocation']
        cur_disb = form.cleaned_data['cur_disb']
        cur_remark = form.cleaned_data['cur_remark']
        subinit_name = form.cleaned_data['subinit_name']
        self.object.init_id = self.object.sub_init_id
        self.object.date_modified = dt.datetime.now()
        self.object.modified_by = self.request.user.username
        
        get_master = self.model.objects.get(subinit_name=self.object.subinit_name, 
                                            sub_init_id=self.object.sub_init_id)
        field_object = self.model._meta.get_field('sub_init_id')
        field_object_alct = self.model._meta.get_field('allocation')
        field_object_rem = self.model._meta.get_field('cur_remark')
        field_object_disb = self.model._meta.get_field('cur_disb')
        
        field_value = getattr(get_master, field_object.attname)
        current_allocation = getattr(get_master, field_object_alct.attname)
        current_remark = getattr(get_master, field_object_rem.attname)
        current_disb = getattr(get_master, field_object_disb.attname)
        
        MasterlistBudgetLog(subinit_name=subinit_name, date_modified=dt.datetime.now(), 
                            sub_init_id=field_value, requestor=self.request.user.username).save()
        
        if cur_disb != current_disb:
            DisburseMinistry(subinit_name=subinit_name, disb=cur_disb, 
                             date_modified=dt.datetime.now(), sub_init_id=field_value, 
                             requestor=self.request.user.username).save()
        
        if cur_remark != current_remark:
            GeneralRemark(subinit_name=subinit_name, remark=cur_remark, 
                          date_modified=dt.datetime.now(), sub_init_id=field_value, 
                          requestor=self.request.user.username).save()
            
        if allocation != current_allocation:
            AllocationMinistry(subinit_name=subinit_name, alct=allocation, 
                               date_modified=dt.datetime.now(), sub_init_id=field_value, 
                               requestor=self.request.user.username).save()
        
        logger.info("Edit initiative " + str(self.object.subinit_name) + " - " + 
                    str(self.request.user.username))
        try:
            packet = [ZabbixMetric('CentOS PODS Dev Master', 'django.log.user_activity', 
                                   "Edit initiative " + str(object.subinit_name) + " - " + 
                                   str(self.request.user.username))]
            zabbix_sender.send(packet)
        except:
            pass
        return super().form_valid(form)
    
    
def convert_to_csv(nameFile, file_ext):
    """_summary_
    Convert any text format to csv

    Args:
        nameFile (_type_): _description_

apps/templates/pid/bulk_update_init.html
{% extends 'layouts/base.html' %}

{% block title %}{% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.7.1/min/dropzone.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
{% endblock stylesheets %}

{% block content %}

<div class="card my-4" style="height: 85vh; align-items: center; margin: 26px;">
    
    <div class="card" style="margin: auto; background-color: transparent; box-shadow: none;">
        <div class="card" style="background-color:#E5E5E5; border-width: 1px; width: 90vh;">
            <div class="container-fluid">
                <div class="card-body pb-0">
                    {% if messages %}
                        {% for message in messages %}
                        <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">             
                            <strong>{{message}}</strong>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>                         
                        {% endfor %}
                    {% endif %} 
                    <h4 class="font-weight-bolder mb-4" style="text-align: center;">MUAT NAIK</h4>
                    <div class="card-body">
                        <form method = "POST" action="{% url 'bulk_update_init' %}" enctype="multipart/form-data" id="form">
                            {% csrf_token %}
                            {{ form.non_field_errors }}
    
                            <div class="form-group">
                                <div class="col">
                                    <div class="row">
                                        <label for="{{ form.Fail.id_for_label }}" class="col-sm-2 col-form-label px-0" style=" float: left; margin: 4px;">Nama Fail:</label>
                                    </div>
                                    <div class="row p-0">
                                    <input type="file" name="Fail" required id="id_Fail" size="60" style="padding-left: 0%;" 
                                    {{ form.Fail }} 
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col">
                                    <div class="row" >
                                        <div class="col mt-4" style="text-align: center;">
                                            <button type="submit" class="btn btn-primary btn-lg" style="background-color: #7AC142; color: white; width: 250px; height: 50px;" id="form_submit_button">
                                                MUAT NAIK
                                            </button>
                                        </div>
                                    </div>

                                    <div class="row" >
                                      <div class="col mt-2 mb-0" style="text-align: center;">
                                        <a href="/masterlist-budget" id="form_submit_button">
                                            <u style="color: blue; font-size: 0.875rem; font-weight: bold; margin: auto; ">KEMBALI</u>
                                        </a>
                                    </div>
                                  </div>
                                </div>

                                
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}
    
<!-- Specific JS goes HERE --> 
{% block javascripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.7.1/min/dropzone.min.js"></script>
    <script type="text/javascript" src="https://unpkg.com/xlsx@0.15.1/dist/xlsx.full.min.js"></script>
{% endblock javascripts %}

apps/templates/pid/editoption.html
{% extends 'layouts/base.html' %}

{% block title %}{% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.7.1/min/dropzone.min.css">
{% endblock stylesheets %}

{% block content %}

<div class="container-fluid py-4">
  <div class="card" style="min-height: 40vh">
      <div class="card-header" style="height: 10%;">
        <h5>
          <b>
              SUNTING INISIATIF
          </b>
        </h5>
      </div>
      <div class="card-body pt-0" style="height: 90%;">
        <div class="form-group">
          <label for="Init" style="margin-bottom:4px; margin-top: 10px;"><h6 style="margin:0px">Kementerian : </h6></label>
          <select class="form-control placeholder" style="background-color: #fff; border-color: lightgray; border-radius:10px">
              <option value="MOF">Kementerian Kewangan Malaysia(MOF)</option>
              <option value="KPWKM">Kementerian Pembangunan Wanita, Keluarga dan Masyarakat(KPWKM)</option>
              <option value="MOH">Kementerian Kesihatan Malaysia(MOH)</option>
              <option value="JPM">Jabatan Perdana Menteri(JPM)</option>
              <option value="MINDEF">Kementerian Pertahanan Malaysia(MINDEF)</option>
              <option value="kPT">Kementerian Pengajian Tinggi(KPT)</option>
              <option value="KPM">kementerian Pendidikan Malaysia(KPM)</option>
              <option value="KKMM">Kementerian Komunikasi dan Digital Malaysia(KKMM)</option>
              <option value="KBS">Kementerian Belia dan Sukan(KBS)</option>
              <option value="MAFI">Kementerian Pertanian & Industri Makanan Malaysia(MAFI)</option>
              <option value="MITI">Kementerian Perdagangan Antarabangsa dan Industri(MITI)</option>
              <option value="KSM">Kementerian Sumber Manusia(KSM)</option>
              <option value="MOSTI">Kementerian Sains, Teknologi dan Inovasi(MOSTI)</option>
              <Option value="KKR">Kementerian Kerja Raya(KKR)</Option>
              <Option value="KPKT">Kementerian Pembangunan Kerajaan Tempatan(KPKT)</Option>
              <Option value="KPN">Kementerian Perpaduan Negara(KPN)</Option>
              <Option value="MEDAC">Kementerian Pembangunan Usahawan dan Koperasi Malaysia(MEDAC)</Option>
              <Option value="KDN">Kementerian Dalam Negeri(KDN)</Option>
              <Option value="MOT">Kementerian Pengangkutan Malaysia(MOT)</Option>
              <Option value="KWP">Kementerian Wilayah Persekutuan(KWP)</Option>
              <Option value="MOTAC">Kementerian Pelancongan dan Kebudayaan(MOTAC)</Option>
              <Option value="KPDNHEP">Kementerian Perdagangan Dalam Negeri dan Kos Sara Hidup(KPDNHEP)</Option>
              <Option value="KETSA">Kementerian Sumber Asli dan Alam Sekitar(KETSA)</Option>
              <Option value="MPIC">Kementerian Perusahaan Perladangan dan Komoditi(MPIC)</Option>
              <Option value="KASA">Kementerian Alam Sekitar dan Air(KASA)</Option>
              <Option value="KPKT">Kementerian Pembangunan Kerajaan Tempatan(KPKT)</Option>
              <Option value="KDN">Kementerian Dalam Negeri(KDN)</Option>
              <Option value="KPLB">Kementerian Kemajuan Desa dan Wilayah(KPLB)</Option>
          </select>
        </div>

        <div class="form-group">
          <label for="Init" style="margin-bottom:4px; margin-top: 10px;"><h6 style="margin:0px">Nama Agensi : </h6></label>
          <input type="text" class="form-control" placeholder="" value="Agensi Pelaksanaan Baru" rows="1" cols="100"Style="background-color: #fff; border-color: lightgray; border-radius:10px">
        </div>
      </div>

      <div class="col" style="text-align: center;">
        <a href="{% url 'listedit' %}">
            <button type="button" class="btn btn-warning btn-lg" style="width: 220px; background-color: #35BAE4;border-color:#35BAE4;">
                SIMPAN
            </button>
        </a>
    </div>
  </div>
</div>
{% endblock content %}
    
<!-- Specific JS goes HERE --> 
{% block javascripts %}
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script type="text/javascript">
function hantar() { 
	let element = document.getElementById("submitbutton");
	Swal.fire({
		title: "Pengesahan Data", 
		text: "Anda pasti anda mahu sahkan penyerahan data?",
		icon: 'warning',
		showCancelButton: true, 
		cancelButtonText: 'Batal',
		cancelButtonWidth: 200,
		confirmButtonColor: '#7AC142',
		cancelButtonColor: '#d33',
		confirmButtonText: ' Ya ',
		allowOutsideClick: false
		}).then((result) => {
			if (result.isConfirmed) {
			Swal.fire({
				position: 'mid',
				icon: 'success',
				text: 'Data telah disahkan',
				showConfirmButton: false,
		})
}
})
}    


</script>
{% endblock javascripts %}

apps/templates/pid/update_init.html
{% extends 'layouts/base.html' %}

{% block title %}{% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.7.1/min/dropzone.min.css">
{% endblock stylesheets %}

{% block content %}
<div class="container-fluid py-4 h-100">
  <div class="row mb-4">
    <div style="height: 74vh;">
      <div class="col" style="height: 100%;">
        <div class="card" style="height: 100%;">
          <div class="card-body p-4" style="height: 10%;">
            <h5><b>SENARAI INISIATIF</b></h5>
          </div>
          <div class="card-body px-0 py-0" style="height: 85%;">
            <div class="table-responsive p-0" style="height: 100%;">
              <table class="table align-items-center justify-content-center mb-0 table table-bordered">
                <thead>
                  <tr>
                    {% for column in workingFile.columns %}
                    <th>
                        {{ column }}
                    </th>
                    {% endfor %}
                  </tr>
                </thead>
                <tbody>
                  {% for index, row in workingFile.iterrows %}
                  <tr>
                    {% for cell in row %}
                    <td>
                      {{ cell }}
                    </td>
                    {% endfor %}
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>  
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row py-4">
  <button id="submitbutton" type="button" class="btn btn-warning btn-lg" 
    style="width: 220px; background-color: #7AC142; margin-left: 10px;">
      HANTAR
  </button>
  <button id="cancelbutton" type="button" class="btn btn-warning btn-lg" style="width:220px; margin-left: 10px;">
    {% csrf_token %}
    BATAL
  </button>
</div>

<input type="hidden" id="refreshed" value="no">
{% endblock content %}
    
<!-- Specific JS goes HERE --> 
{% block javascripts %}
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script type="text/javascript">

  document.getElementById('cancelbutton').addEventListener("click", function() {
    batal('{{file_name}}');
  }, false);

  function batal(file_name){
    var csrftoken = document.querySelector('input[name="csrfmiddlewaretoken"]').value;
    let element = document.getElementById("cancelbutton");
  
    Swal.fire({
      icon: 'warning',
      title: 'Batal Penyerahan?',
      text: 'Anda pasti anda mahu batalkan penyerahan ini?',
      showCancelButton: true,
      cancelButtonText: 'Tidak',
      showLoaderOnConfirm: true,
      confirmButtonText: 'Batal',
      confirmButtonColor: '#DC3A3A',
      focusConfirm: false,
      allowOutsideClick: false
      }).then((result) => {
        if (result.isConfirmed) {
          $.ajax({
            method:'POST',
            url: "{% url 'cancel_submission_masterlist' %}",
            headers: {'X-CSRFToken': csrftoken},
            data : {
              file_name : file_name,
              csrfmiddlewaretoken : csrftoken,
              },
              success:function(data)
              {
                data;
                Swal.fire(
                  {
                    position: 'middle',
                    icon: 'success',
                    text: 'Fail inisiatif telah dipadam',
                    timer: 1500,
                    showConfirmButton: false,
                  })
                .then(function() {
                window.location = '/masterlist-budget';
                })
              }
            })
          }
        })
      }

  onload=function(){
    var e=document.getElementById("refreshed");
    if(e.value=="no")e.value="yes";
    else{e.value="no";location.reload();}
  }

  document.getElementById('submitbutton').addEventListener("click", function() {
    hantar('{{file_name}}');
  }, false);

  function hantar(file_name){
    var csrftoken = document.querySelector('input[name="csrfmiddlewaretoken"]').value;
    let element = document.getElementById("submitbutton");

    Swal.fire({
      icon: 'warning',
      title: 'Sahkan Penyerahan?',
      text: 'Anda pasti anda mahu sahkan penyerahan ini?',
      showCancelButton: true,
      cancelButtonText: 'Tidak',
      showLoaderOnConfirm: true,
      confirmButtonText: 'Sahkan',
      confirmButtonColor: '#7AC142',
      focusConfirm: false,
      allowOutsideClick: false
      }).then((result) => {
        if (result.isConfirmed) {
          $.ajax({
            method:'POST',
            url:"{% url 'submit_masterlist' %}",
            headers: {'X-CSRFToken': csrftoken},
            data : {
              file_name : file_name,
              csrfmiddlewaretoken : csrftoken,
              },
              success:function(data)
              {
                data;
                Swal.fire({
                  position: 'middle',
                  icon: 'success',
                  text: 'Inisiatif anda telah dimuat naik!',
                  timer: 2000,
                  showConfirmButton: false,
                })
                .then(function() {
                window.location = '/masterlist-budget';
                })
              }
            })
          }
        })
      }

  
</script>
{% endblock javascripts %}